"""removed payments table

Revision ID: 7789b3277d50
Revises: 7f66d160be36
Create Date: 2025-05-02 04:49:52.871434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7789b3277d50'
down_revision = '7f66d160be36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('payment_status',
               existing_type=postgresql.ENUM('INITIATED', 'PENDING', 'COMPLETED', 'FAILED', name='paymentstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('delivery_status',
               existing_type=postgresql.ENUM('PENDING', 'SHIPPED', 'DELIVERED', name='deliverystatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('delivery_status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'SHIPPED', 'DELIVERED', name='deliverystatus'),
               existing_nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('INITIATED', 'PENDING', 'COMPLETED', 'FAILED', name='paymentstatus'),
               existing_nullable=False)
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('shipping_cost')

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('result_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('result_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payments_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    # ### end Alembic commands ###
