"""removed postal code in the address table

Revision ID: 77f1672bd70e
Revises: c7b593cd1949
Create Date: 2025-05-01 20:31:09.607335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f1672bd70e'
down_revision = 'c7b593cd1949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
