"""removed billing_info table

Revision ID: dc77b2dcc51e
Revises: 11d54fd3c4ad
Create Date: 2025-05-03 10:47:29.912147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc77b2dcc51e'
down_revision = '11d54fd3c4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_infos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_infos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('card_holder', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('cvv', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='billing_infos_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='billing_infos_pkey')
    )
    # ### end Alembic commands ###
